### ISSUE TITLE
Exposure message is missing the date when first viewing it

### ISSUE THREAD

**Issue by denisedresbach** [project-vagabond/covid-green-app#458]
App version:  iOS 1.0.0.41, Android 1.0.0.41
OS: iOS 13.5.1, Android 10
Device: iPhone SE, Pixel 3XL 
Reproducible: Always

Summary: Simulate exposure results in a message with no date at first view. If I view it again the date is there.

Steps to reproduce:
1. Launch newly installed app and go to settings
2. Tap the version to get debug 
3. Tap Simulate Exposure button
4. Exit app
5. Tap on notification that tells you to view the app

Actual Results: Message seen on screen is missing the date of exposure
Expected Results: The date should be listed in this paragraph
Workaround: Go to My COVID alerts and tap on the red alert. Date will now be in the paragraph.

![IMG_0106](https://user-images.githubusercontent.com/69995161/93368956-80570b80-f803-11ea-848b-accf05f23f0d.PNG)

**Comment by AlanSl** [comment]
@denisedresbach Can you retry in the latest build (42)? For me (checking on Android) a fix for another timing related issue seems to have stopped this from happening.

**Comment by floridemai** [comment]
@denisedresbach Yup, same for me on iOS, with build 42 :)

**Comment by denisedresbach** [comment]
@floridemai @AlanSl How do I get the latest build? I looked at testflight and playstore and don't see an update.

**Comment by AlanSl** [comment]
@denisedresbach What version number does it say at the bottom of the settings screen? Latest version will say 1.0.0.42

**Comment by denisedresbach** [comment]
@AlanSl Got it sorted out. Some strange issue with playstore I guess. All set now Thanks.

**Comment by denisedresbach** [comment]
@floridemai @AlanSl  So far it looks like it is OK in build 42. I see the date at first view. I will do some more testing to be sure.

**Comment by denisedresbach** [comment]
@AlanSl @floridemai  I am seeing this again but in a different flow. 
If Closeness Sensing is not active and I click on the "You've had 1 COVID Alert in the last 14 days" then I see the message with no date. This happens every single time on Android. 
On iOS it is harder to reproduce because I constantly get the popup for exposure notifications and cannot cancel that notification to try the same steps.
Should I open a new ticket for that scenario or do we reopen this one?
Thanks

**Comment by AlanSl** [comment]
Good catch, let's reopen this one

**Comment by AlanSl** [comment]
Should be fixed in build 44

**Comment by denisedresbach** [comment]
Hi @AlanSl @floridemai 
Tried to verify this fix on build 44 by doing the same steps and things got weird.
After the below happened I killed the app and tried again. 'Purple stuck screen' stopped happening, but still see that there is no date in the message.

I have 4 apps installed PA, DE, NY & NJ on my Android.
1. I opened NY app and tapped Simulate Exposure in debug menu, exited out of the app and got the notification to check my app
2. Opened up NJ app and enabled exposure for that app so I could retest the fix in NY
3. Opened up NY app again (1 from home screen 2nd try by the alert) 
Results: All I get is a purple screen
I killed the app and tried again and no longer got the stuck purple screen, **but I do not see a date for this path.**

Maybe I need to test this differently instead of using the other app to disable "closeness sensing".

-Update-
Tested this by putting my phone in airplane mode so Closeness Sensing is not active. I do see a date in this scenario. PASS
Tested the original steps of this bug and see a date for that one too. PASS
Tested disabling by using other apps - FAIL date not seen
TODO- I think there are other paths here that I need to test to figure out what happened with purple stuck screen.

**Comment by denisedresbach** [comment]
@AlanSl @floridemai 
I can reproduce this by below steps (android 1.0.0.45)
Is this a case that needs to be fixed with this ticket or should I open a new ticket since the other paths are fixed?
1. Open NY app and tap Simulate Exposure in debug menu, exit out of the app and get the notification to check app
2. Open up NJ app and enable exposure for that app
3. Open up NY app again by tapping the notification alert
Results: Alert reads with no date

**Comment by AlanSl** [comment]
@denisedresbach Yes, please close this and open another ticket. If that's the only way this problem can now be replicated we can confidently say it's not an issue in regular app usage, and that case needs to be assessed separately because I'm not sure that a real user without access to the debug menu could realistically get in that situation (short of coincidentally switching apps at the moment they received the notification and ignoring the notification until they complete the app switch).

**Comment by denisedresbach** [comment]
Verified fixed 1.0.0.45 
- one remaining issue when using multiple apps and I will open a  new ticket for that one
